language: R
cache: packages
warnings_are_errors: false

addons:
  apt:
     sources:
        - ubuntu-toolchain-r-test
     packages:
        - g++-7

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

install:
  - R -e "install.packages('rstan')"
  - R -e "devtools::install_github('JihongZ/StanDCM')"

script:
  - R -e "rstan::stan_version()"
  - R -e "library(rstan);library(StanDCM);StanDINA.run(Qmatrix, respMatrix, iter=10, init.list='cdm', warmup = 20)"

notifications:
  email:
    on_success: change
    on_failure: change
