language: R
cache: packages
warnings_are_errors: false

before_install:
  - sudo add-apt-repository -y "ppa:marutter/rrutter"
  - sudo add-apt-repository -y "ppa:marutter/c2d4u"
  - sudo apt update
  - sudo apt-get -y install jags r-cran-rjags r-cran-rstan

r:
  - release

notifications:
  email:
    on_success: change
    on_failure: change

